import { json } from '@sveltejs/kit';
import { RequestContext } from '$lib/infra/RequestContext';
import type { RequestHandler } from './$types';

const SEED_MARKER = '[SEED:CONTENT_PIPELINE]';
const STAGES = ['brief', 'shoot', 'edit', 'approval'] as const;
const CONTENT_TYPES = ['youtube', 'instagram', 'tiktok', 'podcast', 'documentary', 'promo', 'interview', 'highlight'] as const;

function escapeFilter(value: string): string {
	return value.replace(/"/g, '\\"');
}

async function clearSeededItems(ctx: any) {
	const filter = `title ~ "${escapeFilter(SEED_MARKER)}" || notes ~ "${escapeFilter(SEED_MARKER)}"`;
	const seededExpenses = await ctx.pb.collection('expenses').getFullList({
		filter: `notes ~ "${escapeFilter(SEED_MARKER)}"`,
		fields: 'id'
	}).catch(() => [] as any[]);

	for (const expense of seededExpenses) {
		const linkedApprovals = await ctx.pb.collection('approvals').getFullList({
			filter: `expenseId = "${expense.id}" || entityId = "${expense.id}"`,
			fields: 'id'
		}).catch(() => [] as any[]);

		for (const approval of linkedApprovals) {
			await ctx.pb.collection('approvals').delete(approval.id).catch(() => undefined);
		}

		await ctx.pb.collection('expenses').delete(expense.id).catch(() => undefined);
	}

	const seededItems = await ctx.pb.collection('content_production').getFullList({
		filter,
		fields: 'id,title'
	});

	if (!seededItems.length) {
		return { deleted: 0, deletedTasks: 0 };
	}

	let deletedTasks = 0;
	for (const item of seededItems) {
		const linkedTasks = await ctx.pb.collection('tasks').getFullList({
			filter: `contentProductionId = "${item.id}"`,
			fields: 'id'
		}).catch(() => []);

		for (const task of linkedTasks) {
			await ctx.pb.collection('tasks').delete(task.id).catch(() => undefined);
			deletedTasks += 1;
		}
	}

	for (const item of seededItems) {
		await ctx.pb.collection('content_production').delete(item.id).catch(() => undefined);
	}

	return { deleted: seededItems.length, deletedTasks };
}

async function seedItems(ctx: any, count: number) {
	const departments = await ctx.pb.collection('departments').getFullList({
		fields: 'id,name',
		sort: 'name'
	});
	if (!departments.length) {
		throw new Error('No departments found. Create departments before seeding content.');
	}

	const defaultDepartment = departments.find((department: any) =>
		String(department?.name ?? '').toLowerCase() === 'media & content buildout'
	) ?? null;

	const projects = await ctx.pb.collection('projects').getFullList({
		fields: 'id,name,department',
		sort: 'name'
	}).catch(() => [] as any[]);

	const requesterProfile = await ctx.pb.collection('user_profiles').getFirstListItem('role = "admin" || role = "leader"', {
		fields: 'id'
	}).catch(() => null as any);

	const fallbackRequester = requesterProfile?.id
		? requesterProfile.id
		: await ctx.pb.collection('user_profiles').getFirstListItem('id != ""', { fields: 'id' })
			.then((profile: any) => profile?.id ?? null)
			.catch(() => null);

	const now = new Date();
	let created = 0;
	let createdApprovals = 0;

	for (let i = 0; i < count; i += 1) {
		const department = defaultDepartment ?? departments[i % departments.length];
		const departmentProjects = projects.filter((p: any) => !p.department || p.department === department.id);
		const project = departmentProjects.length ? departmentProjects[i % departmentProjects.length] : null;
		const stage = STAGES[i % STAGES.length];
		const contentType = CONTENT_TYPES[i % CONTENT_TYPES.length];

		const due = new Date(now);
		due.setDate(due.getDate() + (i % 21) + 1);

		const content = await ctx.pb.collection('content_production').create({
			title: `${SEED_MARKER} Test Content ${String(i + 1).padStart(2, '0')}`,
			contentType,
			stage,
			description: `Seeded content item ${i + 1} for dashboard/content QA.`,
			department: department.id,
			project: project?.id ?? null,
			talent: [],
			assignedTo: null,
			dueDate: due.toISOString(),
			budget: 500 + (i * 125),
			requiresApproval: stage === 'approval',
			approvalStatus: stage === 'approval' ? 'pending' : null,
			paymentStatus: 'pending',
			notes: `${SEED_MARKER} Generated by /api/content/seed`,
			createdBy: ctx.userId
		});

		if (stage === 'approval' && fallbackRequester) {
			const amount = 500 + (i * 125);
			const expense = await ctx.pb.collection('expenses').create({
				description: `${SEED_MARKER} Content approval expense — ${content.title}`,
				amount,
				category: 'Marketing',
				status: 'submitted',
				date: due.toISOString().slice(0, 10),
				submittedBy: fallbackRequester,
				notes: `${SEED_MARKER} Linked contentId=${content.id}`
			}).catch(() => null as any);

			if (expense) {
				await ctx.pb.collection('approvals').create({
					entityType: 'expense',
					entityId: expense.id,
					expenseId: expense.id,
					status: 'pending',
					amount,
					requestedBy: fallbackRequester,
					requestedDate: new Date().toISOString(),
					comments: `<p>${SEED_MARKER} Content approval request for ${content.title}</p>`
				}).catch(() => null);
				createdApprovals += 1;
			}
		}

		created += 1;
	}

	return { created, createdApprovals, marker: SEED_MARKER };
}

export const POST: RequestHandler = async ({ locals, request, url }) => {
	const ctx = await RequestContext.fromApi(locals, url);
	if (!ctx) return json({ message: 'Unauthorized' }, { status: 401 });
	ctx.requireRole('admin', 'leader');

	try {
		const body = await request.json().catch(() => ({}));
		const rawCount = Number(body?.count ?? 18);
		const count = Number.isFinite(rawCount) ? Math.min(200, Math.max(1, Math.floor(rawCount))) : 18;
		const result = await seedItems(ctx, count);
		return json({
			ok: true,
			message: `Seeded ${result.created} content item(s) and ${result.createdApprovals} pending approval request(s).`,
			...result
		});
	} catch (error: any) {
		return json(
			{ message: error?.message ?? 'Failed to seed content test data' },
			{ status: 500 }
		);
	}
};

export const DELETE: RequestHandler = async ({ locals, url }) => {
	const ctx = await RequestContext.fromApi(locals, url);
	if (!ctx) return json({ message: 'Unauthorized' }, { status: 401 });
	ctx.requireRole('admin', 'leader');

	try {
		const result = await clearSeededItems(ctx);

		return json({
			ok: true,
			message: `Cleared ${result.deleted} seeded content item(s).`,
			deleted: result.deleted,
			deletedTasks: result.deletedTasks,
			marker: SEED_MARKER
		});
	} catch (error: any) {
		return json(
			{ message: error?.message ?? 'Failed to clear seeded content' },
			{ status: 500 }
		);
	}
};

export const PATCH: RequestHandler = async ({ locals, request, url }) => {
	const ctx = await RequestContext.fromApi(locals, url);
	if (!ctx) return json({ message: 'Unauthorized' }, { status: 401 });
	ctx.requireRole('admin', 'leader');

	try {
		const body = await request.json().catch(() => ({}));
		const rawCount = Number(body?.count ?? 18);
		const count = Number.isFinite(rawCount) ? Math.min(200, Math.max(1, Math.floor(rawCount))) : 18;

		const cleared = await clearSeededItems(ctx);
		const seeded = await seedItems(ctx, count);

		return json({
			ok: true,
			message: `Reset complete: cleared ${cleared.deleted} and seeded ${seeded.created}.`,
			cleared,
			seeded,
			marker: SEED_MARKER
		});
	} catch (error: any) {
		return json(
			{ message: error?.message ?? 'Failed to reset seeded content' },
			{ status: 500 }
		);
	}
};
