import { Campaign } from '../models/Campaign';
import type { ProjectType, ProjectStatus, ExpenseCategories } from '../schemas';

/**
 * CampaignFactory - Creates Campaign instances with proper defaults
 */
export class CampaignFactory {
	/**
	 * Create a new campaign with defaults
	 */
	static create(data: {
		name: string;
		type: ProjectType;
		managerId: string;
		startDate?: Date;
		endDate?: Date;
		description?: string;
		forecastedExpenses?: number;
		expenseCategories?: ExpenseCategories;
		fiscalYear?: string;
	}): Omit<Campaign, 'id' | 'created' | 'updated'> {
		return new Campaign(
			'', // ID will be generated by repository
			data.name,
			data.type,
			'draft' as ProjectStatus,
			data.managerId,
			data.startDate,
			data.endDate,
			data.description,
			data.forecastedExpenses || 0,
			0, // actualExpenses starts at 0
			data.expenseCategories,
			'pending', // approvalStatus
			undefined, // approvedBy
			data.fiscalYear || new Date().getFullYear().toString(),
			data.forecastedExpenses, // budget same as forecast initially
			undefined, // notes
			undefined, // created
			undefined // updated
		);
	}

	/**
	 * Create a campaign from template
	 */
	static createFromTemplate(template: Campaign, overrides: Partial<Campaign>): Omit<Campaign, 'id' | 'created' | 'updated'> {
		return new Campaign(
			'',
			overrides.name || `${template.name} (Copy)`,
			overrides.type || template.type,
			'draft',
			overrides.managerId || template.managerId,
			overrides.startDate || template.startDate,
			overrides.endDate || template.endDate,
			overrides.description || template.description,
			overrides.forecastedExpenses || template.forecastedExpenses,
			0,
			overrides.expenseCategories || template.expenseCategories,
			'pending',
			undefined,
			overrides.fiscalYear || template.fiscalYear,
			overrides.budget || template.budget,
			overrides.notes,
			undefined,
			undefined
		);
	}

	/**
	 * Create campaign with expense breakdown
	 */
	static createWithExpenseBreakdown(data: {
		name: string;
		type: ProjectType;
		managerId: string;
		startDate?: Date;
		endDate?: Date;
		description?: string;
		expenseCategories: ExpenseCategories;
		fiscalYear?: string;
	}): Omit<Campaign, 'id' | 'created' | 'updated'> {
		// Calculate total from categories
		const totalForecast = Object.values(data.expenseCategories).reduce(
			(sum, amount) => sum + amount,
			0
		);

		return new Campaign(
			'',
			data.name,
			data.type,
			'draft',
			data.managerId,
			data.startDate,
			data.endDate,
			data.description,
			totalForecast,
			0,
			data.expenseCategories,
			'pending',
			undefined,
			data.fiscalYear || new Date().getFullYear().toString(),
			totalForecast,
			undefined,
			undefined,
			undefined
		);
	}

	/**
	 * Create quarterly campaign
	 */
	static createQuarterlyCampaign(data: {
		name: string;
		type: ProjectType;
		managerId: string;
		quarter: 1 | 2 | 3 | 4;
		year: number;
		forecastedExpenses?: number;
		expenseCategories?: ExpenseCategories;
	}): Omit<Campaign, 'id' | 'created' | 'updated'> {
		const quarterStartMonth = (data.quarter - 1) * 3;
		const startDate = new Date(data.year, quarterStartMonth, 1);
		const endDate = new Date(data.year, quarterStartMonth + 3, 0);

		return new Campaign(
			'',
			data.name,
			data.type,
			'draft',
			data.managerId,
			startDate,
			endDate,
			`Q${data.quarter} ${data.year} Campaign`,
			data.forecastedExpenses || 0,
			0,
			data.expenseCategories,
			'pending',
			undefined,
			`${data.year}`,
			data.forecastedExpenses,
			undefined,
			undefined,
			undefined
		);
	}

	/**
	 * Create annual campaign
	 */
	static createAnnualCampaign(data: {
		name: string;
		type: ProjectType;
		managerId: string;
		year: number;
		forecastedExpenses?: number;
		expenseCategories?: ExpenseCategories;
	}): Omit<Campaign, 'id' | 'created' | 'updated'> {
		const startDate = new Date(data.year, 0, 1);
		const endDate = new Date(data.year, 11, 31);

		return new Campaign(
			'',
			data.name,
			data.type,
			'draft',
			data.managerId,
			startDate,
			endDate,
			`${data.year} Annual Campaign`,
			data.forecastedExpenses || 0,
			0,
			data.expenseCategories,
			'pending',
			undefined,
			`${data.year}`,
			data.forecastedExpenses,
			undefined,
			undefined,
			undefined
		);
	}
}
