import path from 'path';
import dotenv from 'dotenv';
import PocketBase from 'pocketbase';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const baseUrl = process.env.POCKETBASE_URL || 'http://127.0.0.1:8090';
const email = process.env.POCKETBASE_ADMIN_EMAIL || '';
const password = process.env.POCKETBASE_ADMIN_PASSWORD || '';
const SEED_MARKER = '[SEED:CONTENT_PIPELINE]';

const stages = ['brief', 'shoot', 'edit', 'approval'] as const;
const contentTypes = ['youtube', 'instagram', 'tiktok', 'podcast', 'documentary', 'promo', 'interview', 'highlight'] as const;

function usage() {
	console.log('Usage: tsx scripts/seed-content-pipeline.ts [count] [--clear]');
	console.log('Examples:');
	console.log('  tsx scripts/seed-content-pipeline.ts');
	console.log('  tsx scripts/seed-content-pipeline.ts 24');
	console.log('  tsx scripts/seed-content-pipeline.ts --clear');
}

async function auth(pb: PocketBase) {
	if (!email || !password) {
		throw new Error('Missing POCKETBASE_ADMIN_EMAIL or POCKETBASE_ADMIN_PASSWORD in .env');
	}
	await pb.admins.authWithPassword(email, password);
}

async function clearSeeded(pb: PocketBase) {
	const seededExpenses = await pb.collection('expenses').getFullList({
		filter: `notes ~ "${SEED_MARKER}"`,
		fields: 'id'
	}).catch(() => [] as any[]);

	for (const expense of seededExpenses) {
		const linkedApprovals = await pb.collection('approvals').getFullList({
			filter: `expenseId = "${expense.id}" || entityId = "${expense.id}"`,
			fields: 'id'
		}).catch(() => [] as any[]);

		for (const approval of linkedApprovals) {
			await pb.collection('approvals').delete(approval.id).catch(() => undefined);
		}

		await pb.collection('expenses').delete(expense.id).catch(() => undefined);
	}

	const filter = `title ~ "${SEED_MARKER}" || notes ~ "${SEED_MARKER}"`;
	const rows = await pb.collection('content_production').getFullList({
		filter,
		fields: 'id,title'
	});

	if (!rows.length) {
		console.log('No seeded content to clear.');
		return;
	}

	let deletedTasks = 0;
	for (const row of rows) {
		const tasks = await pb.collection('tasks').getFullList({
			filter: `contentProductionId = "${row.id}"`,
			fields: 'id'
		}).catch(() => []);

		for (const task of tasks) {
			await pb.collection('tasks').delete(task.id).catch(() => undefined);
			deletedTasks += 1;
		}
	}

	for (const row of rows) {
		await pb.collection('content_production').delete(row.id).catch(() => undefined);
	}

	console.log(`Cleared ${rows.length} seeded content item(s) and ${deletedTasks} linked task(s).`);
}

async function seed(pb: PocketBase, count: number) {
	const departments = await pb.collection('departments').getFullList({ fields: 'id,name' });
	if (!departments.length) {
		throw new Error('No departments found. Seed departments first before seeding content.');
	}

	const defaultDepartment = departments.find((department: any) =>
		String(department?.name ?? '').toLowerCase() === 'media & content buildout'
	) ?? null;

	const projects = await pb.collection('projects').getFullList({
		fields: 'id,name,department',
		sort: 'name'
	}).catch(() => [] as any[]);

	const requesterProfile = await pb.collection('user_profiles').getFirstListItem('role = "admin" || role = "leader"', {
		fields: 'id'
	}).catch(() => null as any);

	const fallbackRequester = requesterProfile?.id
		? requesterProfile.id
		: await pb.collection('user_profiles').getFirstListItem('id != ""', { fields: 'id' })
			.then((profile: any) => profile?.id ?? null)
			.catch(() => null);

	const now = new Date();
	let created = 0;
	let createdApprovals = 0;

	for (let i = 0; i < count; i += 1) {
		const department = defaultDepartment ?? departments[i % departments.length];
		const departmentProjects = projects.filter((p: any) => !p.department || p.department === department.id);
		const project = departmentProjects.length ? departmentProjects[i % departmentProjects.length] : null;
		const stage = stages[i % stages.length];
		const contentType = contentTypes[i % contentTypes.length];
		const due = new Date(now);
		due.setDate(due.getDate() + (i % 21) + 1);

		const content = await pb.collection('content_production').create({
			title: `${SEED_MARKER} Test Content ${String(i + 1).padStart(2, '0')}`,
			contentType,
			stage,
			description: `Seeded content item ${i + 1} for dashboard/content QA.`,
			department: department.id,
			project: project?.id ?? null,
			talent: [],
			assignedTo: null,
			dueDate: due.toISOString(),
			budget: 500 + (i * 125),
			requiresApproval: stage === 'approval',
			approvalStatus: stage === 'approval' ? 'pending' : null,
			paymentStatus: 'pending',
			notes: `${SEED_MARKER} Generated by scripts/seed-content-pipeline.ts`,
			createdBy: pb.authStore.model?.id ?? null
		});

		if (stage === 'approval' && fallbackRequester) {
			const amount = 500 + (i * 125);
			const expense = await pb.collection('expenses').create({
				description: `${SEED_MARKER} Content approval expense — ${content.title}`,
				amount,
				category: 'Marketing',
				status: 'submitted',
				date: due.toISOString().slice(0, 10),
				submittedBy: fallbackRequester,
				notes: `${SEED_MARKER} Linked contentId=${content.id}`
			}).catch(() => null as any);

			if (expense) {
				await pb.collection('approvals').create({
					entityType: 'expense',
					entityId: expense.id,
					expenseId: expense.id,
					status: 'pending',
					amount,
					requestedBy: fallbackRequester,
					requestedDate: new Date().toISOString(),
					comments: `<p>${SEED_MARKER} Content approval request for ${content.title}</p>`
				}).catch(() => null);
				createdApprovals += 1;
			}
		}

		created += 1;
	}

	console.log(`Seeded ${created} content_production item(s) and ${createdApprovals} pending approval request(s). Marker: ${SEED_MARKER}`);
}

async function main() {
	const args = process.argv.slice(2);
	if (args.includes('--help') || args.includes('-h')) {
		usage();
		return;
	}

	const clearOnly = args.includes('--clear');
	const countArg = args.find((a) => /^\d+$/.test(a));
	const count = countArg ? Number(countArg) : 18;

	const pb = new PocketBase(baseUrl);
	pb.autoCancellation(false);
	await auth(pb);

	if (clearOnly) {
		await clearSeeded(pb);
		return;
	}

	await seed(pb, count);
}

main().catch((error) => {
	if (error && typeof error === 'object') {
		console.error(JSON.stringify(error, null, 2));
	}
	console.error(error instanceof Error ? error.stack || error.message : String(error));
	process.exit(1);
});
